config/routes.rb
Rails.application.routes.draw do
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resources 'orders', only: [:index, :show, :create, :destroy]
  put 'orders/:id/add_product/:product_id', action: :add_product, controller: 'orders', as: :order_add_product

  resources 'products', only: [:index, :show, :create, :destroy, :update]
end

app/models/adjustment.rb
class Adjustment < ApplicationRecord
  belongs_to :order
  belongs_to :line_item, optional: true

  after_save :trigger_line_item_price_update

  def trigger_line_item_price_update
    return if line_item.nil?

    line_item.save
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  has_many :adjustments

  before_save :calculate_final_price

  def calculate_final_price
    self.final_price = (price * quantity) - adjustments.pluck(:amount).sum
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :promos
  has_many :line_items
  has_many :adjustments

  AVAILABLE_PROMOS = ["CoffeePromo", "StrawberriesPromo", "TeaPromo"]

  def add_product(product, quantity = 1)
    if line_item = LineItem.find_by(product_id: product.id, order: self.id)
      line_item.quantity += quantity
      line_item.save
    else
      LineItem.create(
        order_id: self.id,
        product_id: product.id,
        price: product.price,
        quantity: quantity
      )
    end

    apply_adjustments
    update_total
  end

  def apply_adjustments
    self.adjustments.destroy_all

    AVAILABLE_PROMOS.each do |promo_class|
      promo_instance = "Promos::#{promo_class}".constantize.new(self.id)
      promo_instance.apply if promo_instance.eligible?
    end
  end

  def update_total
    self.total = line_items_total - adjustments.where(line_item_id: nil).pluck(:amount).sum
    save
  end

  private

  def line_items_total
    line_items.pluck(:final_price).sum
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/promos/basic_promo_rule.rb
module Promos
  class BasicPromoRule
    def initialize(order_id)
      raise "Not implemented"
    end

    def apply(order_id)
      raise "Not implemented"
    end

    def eligible?
      raise "Not implemented"
    end
  end
end

app/models/promos/coffee_promo.rb
module Promos
  class CoffeePromo < BasicPromoRule
    def initialize(order_id)
      @order_id = order_id
    end

    def apply
      Adjustment.create(
        order_id: @order.id,
        line_item_id: @line_item.id,
        amount: @line_item.price * @line_item.quantity * 1/3,
        promo_class: self.class
      )
    end

    def eligible?
      return false unless Order.exists?(@order_id) && Product.find_by(sku: 'CF1')

      @order = Order.find(@order_id)
      @product_id = Product.find_by(sku: 'CF1').id
      @line_item = LineItem.find_by(order_id: @order_id, product_id: @product_id)

      return false if @line_item.nil? || @line_item.quantity < 3

      true
    end
  end
end

app/models/promos/strawberries_promo.rb
module Promos
  class StrawberriesPromo < BasicPromoRule
    def initialize(order_id)
      @order_id = order_id
    end

    def apply
      Adjustment.create(
        order_id: @order.id,
        line_item_id: @line_item.id,
        amount: 0.5 * @line_item.quantity,
        promo_class: self.class
      )
    end

    def eligible?
      return false unless Order.exists?(@order_id) && Product.find_by(sku: 'SR1')

      @order = Order.find(@order_id)
      @product_id = Product.find_by(sku: 'SR1').id
      @line_item = LineItem.find_by(order_id: @order_id, product_id: @product_id)

      return false if @line_item.nil? || @line_item.quantity < 3

      true
    end
  end
end

app/models/promos/tea_promo.rb
module Promos
  class TeaPromo < BasicPromoRule
    def initialize(order_id)
      @order_id = order_id
    end

    def apply
      multiplier = @line_item.quantity / 2
      Adjustment.create(
        order_id: @order.id,
        line_item_id: @line_item.id,
        amount: @line_item.price * multiplier,
        promo_class: self.class
      )
    end

    def eligible?
      return false unless Order.exists?(@order_id) && Product.find_by(sku: 'GR1')

      @order = Order.find(@order_id)
      @product_id = Product.find_by(sku: 'GR1').id
      @line_item = LineItem.find_by(order_id: @order_id, product_id: @product_id)

      return false if @line_item.nil? || @line_item.quantity < 2

      true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @line_items = LineItem.includes(:product).where(order_id: params[:id])
    @products = Product.all
  end

  def create
    @order = Order.create
    redirect_to order_url(@order)
  end

  def add_product
    @order = Order.find(params[:id])
    @order.add_product(Product.find(params[:product_id]))
    redirect_to order_url(@order)
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
    redirect_to orders_url
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy!
    redirect_to products_url, notice: "Product was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.fetch(:product, {}).permit(:name, :sku, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>Amenitiz challenge</h1>

<%= link_to 'Products', products_path %>
<%= link_to 'Orders', orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmenitizChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to 'Home', root_path %>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders</h1>

<%= button_to 'Create Order', orders_path, method: :create %>

<% @orders.each do |order| %>
  <p><%= link_to "Order N: #{order.id}", order %> Total <%= order.total %></p>
<% end %>

app/views/orders/show.html.erb
<h1>Order number: <%= @order.id %></h1>
<%= button_to 'Destroy Order', order_path(@order), method: :delete %>
<%= link_to 'Back', orders_path %>

<h1>Order</h1>
<% @line_items.each do |line_item| %>
  <p>
    <%= line_item.product.name %> x<%= line_item.quantity %> <%= line_item.final_price %>
  </p>
<% end %>
<p>Total: <%= @order.total %></p>

<h1>Products</h1>
<% @products.each do |product| %>
  <p>
    <%= button_to '+', order_add_product_path(@order.id, product.id), method: :put %>
    <%= product.name %>
    <%= product.sku %>
    <%= product.price %>
  </p>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <p>Name: <%= form.text_field :name %></p>
  <p>Sku: <%= form.text_field :sku %></p>
  <p>Price: <%= form.text_field :price %></p>

  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <%= link_to product.name, product %> -
  <%= product.sku %> -
  <%= product.price %>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>